version: '3'
services:
 mysql_db:
    image: 'mysql:8.0.28'
    volumes:
    - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
    - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: test
     MYSQL_USER: USER 
